spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mask_sale?serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mqtt:
    username: mask
    password: ljhLJH080230.
    url: tcp://192.168.0.11:1883
    client:
      id: 'maskId'
    default:
      topic: 'topic'
    topics: mask
    qosValues: 2,3

server:
  port: 80
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


